
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftEQUIVALENCEleftIMPLIESleftORleftANDrightNOTAND ATOM EQUIVALENCE IMPLIES LPAREN NOT OR RPARENformula : ATOMformula : NOT formulaformula : formula OR formulaformula : formula AND formulaformula : formula IMPLIES formulaformula : formula EQUIVALENCE formulaformula : LPAREN formula RPAREN'
    
_lr_action_items = {'$end':([2,4,10,11,12,13,14,15,],[0,-1,-2,-7,-5,-4,-6,-3,]),'RPAREN':([4,5,10,11,12,13,14,15,],[-1,11,-2,-7,-5,-4,-6,-3,]),'AND':([2,4,5,10,11,12,13,14,15,],[7,-1,7,-2,-7,7,-4,7,7,]),'LPAREN':([0,1,3,6,7,8,9,],[1,1,1,1,1,1,1,]),'EQUIVALENCE':([2,4,5,10,11,12,13,14,15,],[8,-1,8,-2,-7,-5,-4,-6,-3,]),'NOT':([0,1,3,6,7,8,9,],[3,3,3,3,3,3,3,]),'ATOM':([0,1,3,6,7,8,9,],[4,4,4,4,4,4,4,]),'IMPLIES':([2,4,5,10,11,12,13,14,15,],[6,-1,6,-2,-7,-5,-4,6,-3,]),'OR':([2,4,5,10,11,12,13,14,15,],[9,-1,9,-2,-7,9,-4,9,-3,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'formula':([0,1,3,6,7,8,9,],[2,5,10,12,13,14,15,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> formula","S'",1,None,None,None),
  ('formula -> ATOM','formula',1,'p_formula_atom','pl.py',49),
  ('formula -> NOT formula','formula',2,'p_formula_not','pl.py',53),
  ('formula -> formula OR formula','formula',3,'p_formula_or','pl.py',57),
  ('formula -> formula AND formula','formula',3,'p_formula_and','pl.py',61),
  ('formula -> formula IMPLIES formula','formula',3,'p_formula_implies','pl.py',65),
  ('formula -> formula EQUIVALENCE formula','formula',3,'p_formula_equivalence','pl.py',69),
  ('formula -> LPAREN formula RPAREN','formula',3,'p_factor_expr','pl.py',73),
]
