# -*- coding: utf-8 -*-

ldlf_formulas = [
    "tt",
    "ff",
    "!tt",
    "!ff",
    "tt & tt",
    "tt & ff",
    "ff & ff",
    "tt | ff",
    "<true>tt",
    "<true>ff",
    "[true]tt",
    "[true]ff",
    "<A>tt",
    "<A>ff",
    "[A]tt",
    "[A]ff",
    "<A & B>tt",
    "<A & B>ff",
    "<A | C>tt",
    "<A | C>ff",
    "<A + B>tt",
    "<A + B>ff",
    "<A ; B>tt",
    "<A ; B>ff",
    "<A*>tt",
    "<A*>ff",
    "<<A>tt?>tt",
    "<<A>tt?>ff",
    "[A & B]tt",
    "[A & B]ff",
    "[A | C]tt",
    "[A | C]ff",
    "[A + B]tt",
    "[A + B]ff",
    "[A ; B]tt",
    "[A ; B]ff",
    "[A*]tt",
    "[A*]ff",
    "[<A>tt?]tt",
    "[<A>tt?]ff",
]


ltlf_formulas = [
    "a",
    "!a",
    "a | b",
    "a & b",
    "X a",
    "WX a",
    "(X a) <-> !(WX(!a))",
    "(WX a) <-> !(X(!a))",
    "a U b",
    "a R b",
    "F a",
    "F(a & b)",
    "F(a | b)",
    "F(a & last)",
    "G a",
    "F(G(a))",
    "G(F(a))",
    "G(true)",
    "F(true)",
    "G(false)",
    "F(false)",
    "last",
    # "end",
    "true",
    "false",
    "a -> b",
    "a <-> b",
    "G(a -> b)",
    "G(a -> F(b))",
    "G(a -> b -> c)",
]
